# Generated by Django 4.0.5 on 2022-07-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
    ]
