# Generated by Django 4.0.5 on 2022-07-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='distance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
