# Generated by Django 4.0.5 on 2022-07-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_exercise_weight_alter_exercise_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Textual Notes'),
        ),
    ]
