# Generated by Django 4.0.5 on 2022-07-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_remove_workout_end_time_alter_exercise_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
